megawave-2.10 import
downloaded on 2009-02-27 from
http://megawave.cmla.ens-cachan.fr/distribution/MegaWave2_V2.10.tar.gz

diff --git a/kernel/shell/cmw2 b/kernel/shell/cmw2
--- a/kernel/shell/cmw2
+++ b/kernel/shell/cmw2
@@ -2,11 +2,11 @@
 #--------------------------- Shell MegaWave2 Macro --------------------------#
 _sccsid="%Z%MegaWave2 %R%, %M% %I%, %G%";
 _Prog="`basename $0`"
-_Vers="1.43"
-_Date="2000"
+_Vers="1.47"
+_Date="2002"
 _Func="Compile a MegaWave2 Module or Macro";
 _Auth="Jacques Froment, Sylvain Parrino";
-_Usage=" [-gnu] [-g] [-X] [-O] [-c compiler_option] [-Dname[=def]] [-Uname] [-Ipathname] [-w] [-Ldirectory] [-llibrary] [-dep] [-pubsyslib] [-N] module"
+_Usage=" [-gnu] [-g] [-X] [-O] [-v] [-c compiler_option] [-Dname[=def]] [-Uname] [-Ipathname] [-w] [-Ldirectory] [-llibrary] [-dep] [-pubsyslib] [-N] module"
 #----------------------------------------------------------------------------
 # This file is part of the MegaWave2 system macros. 
 # MegaWave2 is a "soft-publication" for the scientific community. It has
@@ -15,6 +15,45 @@ _Usage=" [-gnu] [-g] [-X] [-O] [-c compiler_option] [-Dname[=def]] [-Uname] [-Ip
 # CMLA, Ecole Normale Superieure de Cachan, 61 av. du President Wilson,
 #       94235 Cachan cedex, France. Email: megawave@cmla.ens-cachan.fr 
 #-----------------------------------------------------------------------------
+
+# Remove given file(s) if verbose flag not set; if set, output file name.
+
+remove()
+
+{
+ if [ $verbose -ne 1 ]; then
+  /bin/rm -f $1
+ else
+  for f in $1 
+  do
+  if [ -f $f ]; then
+   mwechon "<File $f> "
+   case "$f" in
+    $TEXFILE) : 
+    echo "tex file."
+    ;;
+    $NMFILE) :
+    echo "path of the module file."
+    ;;
+    $IIFILE) :
+    echo "syntax of the module (to be used by interpreters)."
+    ;;
+    $ICFILE) :
+    echo "mwicmd[] tab." 
+    ;;
+    $AAFILE) :
+    echo "main file to call the module (run-time command mode)."
+    ;;
+    $MFILE) :
+    echo "preprocessed module."
+    ;;
+    $XMWFILE) :
+    echo "main file to call the module (XMegaWave2 mode)."
+   esac
+  fi
+  done
+ fi
+}
 
 echo " "
 echo ">>> Welcome on the MegaWave2 Compiler V${_Vers} <<<"
@@ -90,9 +129,9 @@ fi
 # Check if the current directory is a subdir of $MY_MEGAWAVE2 (user mode)
 # or of $MEGAWAVE2 (adm mode). So we do not need anymore -adm.
 
-dir=`pwd | grep $MY_MEGAWAVE2`
+dir=`/bin/pwd | grep $MY_MEGAWAVE2`
 if [ "$dir" = "" ]; then
- dir=`pwd | grep $MEGAWAVE2`
+ dir=`/bin/pwd | grep $MEGAWAVE2`
  if [ "$dir" = "" ]; then
   echo "Your current directory is not valid. You must compile modules into subdir of"
   echo "$MY_MEGAWAVE2/src (user mode) or of $MEGAWAVE2/src (adm mode)."
@@ -185,6 +224,7 @@ MAINOBJ="$MWDIR/sys/lib/$MW_MACHINETYPE/mw_main.o"
 LOPTS="$MAINOBJ $LOPTS -L$MWDIR/sys/lib/$MW_MACHINETYPE -L$MWDIR/lib/$MW_MACHINETYPE"
 debug=0
 dep=0
+verbose=0
 
 while [ "$1" != "" -a "$STOP" = "FALSE" ]
 do
@@ -197,6 +237,10 @@ do
 
     -d)		MWOPTS="$MWOPTS -d"
 		;;
+
+    -v)         verbose=1
+                ;;
+		
     # MegaWave 2 preprocessor options
     -D*|-I*|-U*) MWOPTS="$MWOPTS $1"
 		;;
@@ -332,8 +376,8 @@ XMWFILE=$TMP/mw$$X.c
 LINKFILE=$TMP/mw$$D.link
 
 # new trap
-trap "echo interrupt; /bin/rm -f $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE; exit 1" 2
-trap "echo quit; /bin/rm -f $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE; exit 1" 3
+trap "echo interrupt; remove $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE $XMWFILE $LINKFILE; exit 1" 2
+trap "echo quit; remove $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE $XMWFILE $LINKFILE; exit 1" 3
 
 MWCMD="$MWCMD"
 MWARG="$IX11 $MWOPTS -_T$TEXFILE -_I$IIFILE -_A$AAFILE -_M$MFILE -_N$NMFILE $MWFILE"
@@ -344,7 +388,10 @@ fi
 
 echo " "
 echo "  Phase 1 : MegaWave2 preprocessor"
-#echo "-> $MWCMD $MWARG"
+#-------------------------------------------------------
+if [ $verbose -eq 1 ]; then
+ echo "<Run> $MWCMD $MWARG"
+fi
 sh -c "$MWCMD $MWARG"
 
 CMW2_RET=$?
@@ -357,15 +404,15 @@ if [ $CMW2_RET -ne 0 ]; then
      lint -u $MWOPTS $IX11 $MWFILE| more
     fi
    fi
-   /bin/rm -f $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE
+   remove $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE
    exit 1
 else
   TOTNAME=`cat $NMFILE`
   MODULE=`basename $TOTNAME`
   GROUP="`dirname $TOTNAME`"
-  /bin/rm -f $NMFILE
+  remove $NMFILE
   echo "  Phase 2 : production of sources and objects"
-
+#-------------------------------------------------------
   echo "          production of document squeleton (doc/obj/$MODULE.doc)"
   if [ ! -d $MWDESTDIR/doc/obj ]; then
     mwechon "  Creating '$MWDESTDIR/doc/obj' : "
@@ -375,6 +422,7 @@ else
   mv $TEXFILE $MWDESTDIR/doc/obj/$MODULE.doc
 
   echo "          production of arguments analyser object"
+#-------------------------------------------------------
   if [ ! -d $MWDESTDIR/obj/$MW_MACHINETYPE ]; then
     mwechon "  Creating '$MWDESTDIR/obj/$MW_MACHINETYPE' : "
     mkdir -p $MWDESTDIR/obj/$MW_MACHINETYPE
@@ -382,58 +430,83 @@ else
   fi
   CCCMD="$CC -D$MW_SYSTEMTYPE -D$MW_MACHINETYPE -c $OPTIM $COPTS -o $MWDESTDIR/obj/$MW_MACHINETYPE/m_$MODULE.o $AAFILE"
   #EXTOBJ="$EXTOBJ $MWDESTDIR/obj/$MW_MACHINETYPE/m_$MODULE.o"
-  #echo "-> $CCCMD"
+
+  if [ $verbose -eq 1 ]; then
+   echo "<Run> $CCCMD"
+  fi
   sh -c "$CCCMD"
+
   if [ $? -ne 0 ]; then
     echo "          Error : exit."
-    /bin/rm -f $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE
+    remove $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE
     exit 1
   fi
-  /bin/rm -f $AAFILE
+  remove $AAFILE
 
   echo "          production of module object"
+#-------------------------------------------------------
   CCCMD="$CC -D$MW_SYSTEMTYPE -D$MW_MACHINETYPE -c $COPTS -o $MWDESTDIR/obj/$MW_MACHINETYPE/$MODULE.o $MFILE"
   #EXTOBJ="$EXTOBJ $MWDESTDIR/obj/$MW_MACHINETYPE/$MODULE.o"
-  #echo "-> $CCCMD"
+
+  if [ $verbose -eq 1 ]; then
+   echo "<Run> $CCCMD"
+  fi
   sh -c "$CCCMD"
   if [ $? -ne 0 ]; then
     echo "          Error : exit."
-    /bin/rm -f $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE
+    remove $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE
     exit 1
   fi
-  /bin/rm -f $MFILE
+  remove $MFILE
+
   echo "          add objects to MegaWave2 user library"
+#-------------------------------------------------------
   if [ ! -d $MWDESTDIR/lib/$MW_MACHINETYPE ]; then
     mwechon "  Creating '$MWDESTDIR/lib/$MW_MACHINETYPE' : "
     mkdir -p $MWDESTDIR/lib/$MW_MACHINETYPE
     echo "done."
   fi
-  ar r $MWDESTDIR/lib/$MW_MACHINETYPE/lib$ULIB.a $MWDESTDIR/obj/$MW_MACHINETYPE/m_$MODULE.o $MWDESTDIR/obj/$MW_MACHINETYPE/$MODULE.o
-
+  CCCMD="ar r $MWDESTDIR/lib/$MW_MACHINETYPE/lib$ULIB.a $MWDESTDIR/obj/$MW_MACHINETYPE/m_$MODULE.o $MWDESTDIR/obj/$MW_MACHINETYPE/$MODULE.o"
+  if [ $verbose -eq 1 ]; then
+   echo "<Run> $CCCMD"
+  fi
+  sh -c "$CCCMD"
+  if [ $? -ne 0 ]; then
+    echo "          Error : exit."
+    remove $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE
+    exit 1
+  fi
   # Ranlib is needed for SunOS 4.x
   if [ $MW_SYSTEMTYPE = SunOS ] && [ $MW_MACHINETYPE != sun4_5 ]; then
     ranlib $MWDESTDIR/lib/$MW_MACHINETYPE/lib$ULIB.a
   fi
 
   echo "          production of interface with MegaWave2 interpretor source"
+#-------------------------------------------------------
   if [ ! -d $MWDESTDIR/mwi ]; then
     mwechon "  Creating '$MWDESTDIR/mwi' : "
     mkdir -p $MWDESTDIR/mwi
     echo "done."
   fi
   CCCMD="/bin/mv $IIFILE $MWDESTDIR/mwi/int_$MODULE.c"
-  #echo "-> $CCCMD"
+  if [ $verbose -eq 1 ]; then
+   echo "<Run> $CCCMD"
+  fi
   sh -c "$CCCMD"
   
   if [ $XMW = 1 ]; then
     echo "          production of interface with XMegaWave2"
+#-------------------------------------------------------
     CCCMD="$CC $IX11 $IXm -D$MW_SYSTEMTYPE -D$MW_MACHINETYPE -c $OPTIM $COPTS -o $MWDESTDIR/obj/$MW_MACHINETYPE/x_$MODULE.o $XMWFILE"
-    # echo "-> $CCCMD"
+    if [ $verbose -eq 1 ]; then
+     echo "<Run> $CCCMD"
+    fi
     sh -c "$CCCMD"
-    /bin/rm -f $XMWFILE
+    remove $XMWFILE
   fi
   
   echo "          production of interface with MegaWave2 library object"
+#-------------------------------------------------------
   echo '#define MWI_DEC'                       >$ICFILE
   echo '#include "mwi.h"'                     >>$ICFILE
   echo 'int mwind = 0;'                       >>$ICFILE
@@ -444,17 +517,20 @@ else
   echo '};'                                   >>$ICFILE
   CCCMD="$CC -D$MW_SYSTEMTYPE -D$MW_MACHINETYPE -c $OPTIM $COPTS -o $MWDESTDIR/obj/$MW_MACHINETYPE/i_$MODULE.o $ICFILE"
   EXTOBJ="$EXTOBJ $MWDESTDIR/obj/$MW_MACHINETYPE/i_$MODULE.o"
-  #echo "-> $CCCMD"
+  if [ $verbose -eq 1 ]; then
+   echo "<Run> $CCCMD"
+  fi
   sh -c "$CCCMD"
   if [ $? -ne 0 ]; then
     echo "          Error : exit."
-    /bin/rm -f $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE
+    remove $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE
     exit 1
   fi
-  /bin/rm -f $ICFILE
+  remove $ICFILE
 
   if [ $XMW = 1 ]; then  
    echo "          add objects to XMegaWave2 user interface library"
+#-------------------------------------------------------
    ar r $MWDESTDIR/lib/$MW_MACHINETYPE/lib$XULIB.a $MWDESTDIR/obj/$MW_MACHINETYPE/i_$MODULE.o $MWDESTDIR/obj/$MW_MACHINETYPE/x_$MODULE.o
    # Ranlib is needed for SunOS 4.x
    if [ $MW_SYSTEMTYPE = SunOS ] && [ $MW_MACHINETYPE != sun4_5 ]; then
@@ -486,17 +562,13 @@ else
   fi
 
   echo "  Phase 3 : production of MegaWave command"
+#-------------------------------------------------------
   # Teste acces de la directory des executables
   if [ ! -d $MWDESTDIR/bin/$MW_MACHINETYPE ]; then
     mwechon "  Creating '$MWDESTDIR/bin/$MW_MACHINETYPE' : "
     mkdir -p $MWDESTDIR/bin/$MW_MACHINETYPE
     echo "done."
   fi
-#  if [ ! -w $MWDESTDIR/bin/$MW_MACHINETYPE ] || [ ! -r $MWDESTDIR/include ] || \
-#     [ ! -r ${MWDIR?'environment not set'}/include ]; then
-#     echo "`basename $0` : You are not allowed to generate MegaWave User's command" 1>&2
-#     exit 4
-#  fi  
 
   # Teste si nouvelle commande ou non
   if [ -x $MWDESTDIR/bin/$MW_MACHINETYPE/$MODULE ] || \
@@ -548,12 +620,15 @@ else
 
 
   LINKCMD="$CC $LOPTS -o $MWDESTDIR/bin/$MW_MACHINETYPE/$MODULE $EXTOBJ $OBJ $LULIB $LADM_LIBMW $SYS_LIBMW $HPLIBS $ALIBS $ASLIBS"
-# echo "-> $LINKCMD"
+  if [ $verbose -eq 1 ]; then
+   echo "<Run> $LINKCMD"
+  fi
   sh -c "$LINKCMD"
   if [ $? -ne 0 ]; then
-    echo "          Error : exit."
-    /bin/rm -f $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE
-    exit 1
+    echo "          Link failed : exit."
+    remove $TEXFILE $IIFILE $ICFILE $AAFILE $MFILE $NMFILE
+#  Exit 2 to detect error due to link
+    exit 2
   fi
 
 # Dependencies list, if asked 
@@ -563,10 +638,12 @@ else
     DEPEXTOBJ="$EXTOBJ $MWDESTDIR/obj/$MW_MACHINETYPE/m_$MODULE.o"
     DEPEXTOBJ="$DEPEXTOBJ $MWDESTDIR/obj/$MW_MACHINETYPE/$MODULE.o"
     DEPLINKCMD="$CC $LOPTS -o $LINKFILE $DEPEXTOBJ $OBJ $SYS_LIBMW $HPLIBS $ALIBS $ASLIBS 2> $MWDESTDIR/doc/obj/DEPENDENCIES/$MODULE.mis"
-#echo "-> $DEPLINKCMD"
+    if [ $verbose -eq 1 ]; then
+     echo "<Run> $DEPLINKCMD"
+    fi
     sh -c "$DEPLINKCMD"
     if [ $? = 0 ]; then
-      /bin/rm -f $MWDESTDIR/doc/obj/DEPENDENCIES/$MODULE.mis
+      remove $MWDESTDIR/doc/obj/DEPENDENCIES/$MODULE.mis
       echo "" > $MWDESTDIR/doc/obj/DEPENDENCIES/$MODULE.dep
     else
       echo "\SeeAlso{Dependencies list not available (run mwdep) !}"  > $MWDESTDIR/doc/obj/DEPENDENCIES/$MODULE.dep
@@ -576,7 +653,7 @@ else
   fi
 
   if [ -f $LINKFILE ]; then
-    /bin/rm -f $LINKFILE
+    remove $LINKFILE
   fi
 
   if [ -x $MWDESTDIR/bin/$MW_MACHINETYPE/$MODULE ]; then
@@ -585,7 +662,7 @@ else
      strip $MWDESTDIR/bin/$MW_MACHINETYPE/$MODULE
     fi
     if  [ $NEW -eq 1 ]; then
-       echo "     (New command added... Type rehash)"
+       echo "     (New command added)"
     fi
   fi
 
diff --git a/kernel/shell/cmw2_all b/kernel/shell/cmw2_all
--- a/kernel/shell/cmw2_all
+++ b/kernel/shell/cmw2_all
@@ -1,12 +1,12 @@
-#! /bin/sh 
+#!/bin/sh 
 #--------------------------- Shell MegaWave Macro ----------------------------#
 _sccsid="%Z%MegaWave2 %R%, %M% %I%, %G%";
 _Prog="`basename $0`"
-_Vers="1.15";
-_Date="1999";
+_Vers="1.22";
+_Date="1999-2002";
 _Func="Compile all MegaWave2 modules and user's macros, recursively on each subdirectory";
 _Auth="Jacques Froment";
-_Usage="[-gnu] [-clear] [-g] [-X] [-O] [-c compiler_option] [-Dname[=def]] [-Uname] [-Ipathname] [-w] [-Ldirectory] [-llibrary] [-2p] [-sp] [-dep] [-pubsyslib] [-force] [-N errorfile] group_directory"
+_Usage="[-gnu] [-clear] [-g] [-X] [-O] [-c compiler_option] [-Dname[=def]] [-Uname] [-Ipathname] [-w] [-Ldirectory] [-llibrary] [-2p] [-sp] [-dep] [-pubsyslib] [-force] [-N processid] group_directory"
 
 #----------------------------------------------------------------------------#
 # This file is part of the MegaWave2 system macros. 
@@ -35,8 +35,16 @@ fi
 
 force=0
 clear=0
+
+# 1 if two-pass process asked (set at the first call only)
 twopass=0
+
+# -fp if first-pass in the two-pass process
+firstpass=""
+
+# -sp if second-pass
 secondpass=""
+
 cmw_opt=""
 
 while [ "$1" != "" ]
@@ -60,6 +68,10 @@ do
 	    shift
             ;;
 
+    "-fp")  firstpass=-fp
+	    shift
+            ;;
+
     "-dep") cmw_opt="$cmw_opt -dep"
             shift
             ;;
@@ -75,9 +87,10 @@ do
 
     -N)   NoDisplay=yes;
           shift;
-          errorfile=$1;
+          processid=$1;
           shift;
           ;;
+
           
     -g)   cmw_opt="$cmw_opt -g";
           shift;
@@ -91,7 +104,7 @@ do
     		shift
     		;;
 
-    -O)         cmw_opt="$cmw_opt -O"
+    -O*)        cmw_opt="$cmw_opt $1"
     		shift
     		;;
 
@@ -126,9 +139,9 @@ if [ ! -d $dir ]; then
   exit 2
 fi
 
-CWD=`pwd`
+CWD=`/bin/pwd`
 cd $dir
-TD=`pwd`
+TD=`/bin/pwd`
 cd $CWD
 MWDESTDIR=`echo $TD | grep $MY_MEGAWAVE2`
 if [ "$MWDESTDIR" = "$TD" ]; then
@@ -146,6 +159,11 @@ else
     echo "$_Prog : Directory '$dir' is not a subdir of \$MY_MEGAWAVE2 or of \$MEGAWAVE2" 1>&2
     exit 3
   fi
+fi
+
+TMP=/usr/tmp
+if  [ ! -w $TMP ]; then
+  TMP=/tmp
 fi
 
 if [ "$NoDisplay" != "yes" ]; then
@@ -218,7 +236,9 @@ if [ "$NoDisplay" != "yes" ]; then
 # End clear
  fi
 
-errorfile=/usr/tmp/cmw2_all_$$.error
+processid=$$
+errorfile=$TMP/cmw2_all_${processid}.error
+
 echo "List of unsuccessful compilations :" > $errorfile
 echo "--------------------------------- " >> $errorfile
 echo '' >> $errorfile
@@ -236,9 +256,14 @@ echo ''
 # End first entry for this command
 fi
 
+errorfile=$TMP/cmw2_all_${processid}.error
+erroroccured=$TMP/cmw2_all_${processid}.erroroccured
+stdout=$TMP/cmw2_all_${processid}.stdout
+stderr=$TMP/cmw2_all_${processid}.stderr
+
 # trap
-trap "echo interrupt; /bin/rm -f $errorfile; exit 1" 2
-trap "echo quit; /bin/rm -f $errorfile; exit 1" 3
+trap "echo interrupt; /bin/rm -f $errorfile $erroroccured $stdout; exit 1" 2
+trap "echo quit; /bin/rm -f $errorfile $erroroccured $stderr; exit 1" 3
 
 if [ $twopass = 1 ]; then
   echo '' >> $errorfile
@@ -249,7 +274,7 @@ if [ $twopass = 1 ]; then
   echo 'Beginning First pass...'
   echo '-----------------------'
   echo ' '
-  cmw2_all $cmw_opt -N $errorfile ${dir}
+  cmw2_all $cmw_opt -fp -N $processid ${dir}
   echo '' >> $errorfile
   echo 'Second pass:' >> $errorfile
   echo '' >> $errorfile
@@ -267,15 +292,22 @@ do
     if [ "$secondpass" != "-sp" ] || 
 	[ ! -x $MWDESTDIR/bin/$MW_MACHINETYPE/`basename $file .c` ]; then 
 	mwechon "$file "
-        (cd ${dir}; cmw2 -N $cmw_opt $file >> /dev/null 2>> /dev/null;)
-      if [ $? -ne 0 ]; then
+        (cd ${dir}; cmw2 -N $cmw_opt $file 1>> $stdout 2>> $stderr;)
+	retcmw=$?
+	if [ $retcmw -ne 0 ]; then
          echo "${dir}/${file}" >> $errorfile
-	 mwechon "(failed) " 
-      fi
+# retcmw = 2 : error due to failed link (unknown reference)
+         if [ $retcmw -ne 2 ] || [ "$secondpass" = "-sp" ] || [ "$firstpass" = "" ]; then
+	  mwechon "(failed) " 
+          touch $erroroccured
+         else
+          mwechon "(delayed) "
+         fi
+	fi
     fi
   else
    echo "---> Scan Subdirectory ${dir}/${file} <---"
-   cmw2_all $cmw_opt $secondpass -N $errorfile ${dir}/${file}
+   cmw2_all $cmw_opt $firstpass $secondpass -N $processid ${dir}/${file}
    echo ''
    echo ''
   fi
@@ -283,16 +315,24 @@ done
 
 if [ "$NoDisplay" != "yes" ]; then
 
-echo ''
-mwechon "------ End at "
-date
-echo ''
+ echo ''
+ mwechon "------ End at "
+ date
+ echo ''
 
-cat $errorfile
-\rm $errorfile
-echo ''
-
+ if [ -f $erroroccured ]; then
+  cat $errorfile
+  echo ''
+  rm -f $errorfile $erroroccured $stdout $stderr
+  exit 1
+ else
+  echo "All modules were successfully compiled !"
+  echo ''
+  rm -f $errorfile $stdout $stderr
+  exit 0
+ fi
 fi
+
 exit 0
 
 
diff --git a/kernel/shell/mwinstall b/kernel/shell/mwinstall
--- a/kernel/shell/mwinstall
+++ b/kernel/shell/mwinstall
@@ -1,10 +1,10 @@
-#!/bin/sh
+#!/bin/sh 
 #--------------------------- Shell MegaWave2 Macro --------------------------#
 _sccsid="%Z%MegaWave %R%, %M% %I%, %G%";
 _Func="Install a new MegaWave2 full version (adm only)";
 _Prog="`basename $0`"
-_Vers="1.6"
-_Date="1999-2000"
+_Vers="1.14"
+_Date="1999-2002"
 _Auth="Jacques Froment";
 _Usage="[-static] [-public || -public=private] [-clear] [-debug] [-level l] mw2distribution"
 #-----------------------------------------------------------------------------
@@ -31,11 +31,18 @@ _Usage="[-static] [-public || -public=private] [-clear] [-debug] [-level l] mw2d
 # -level l : Install levels greater or equal than l only.
 #-----------------------------------------------------------------------------
 
+Echo()
+
+{
+ echo "$1"
+ echo "$1" >> $MWSRC/Install.log
+}
+
 NewTrap()
 {
-trap "echo '***********************************'; \
-      echo '***** Installation canceled ! *****'; \
-      echo '***********************************';\
+trap "Echo '***********************************'; \
+      Echo '***** Installation canceled ! *****'; \
+      Echo '***********************************';\
       Abort" 2 3
 }
 
@@ -45,9 +52,9 @@ Answer()
 ok=0
 while [ $ok -ne 1 ]; do
  if  [ "$2" != "" ]; then
-   echo "$1 [Y/N] ? [default $2]" 2>&1
+   Echo "$1 [Y/N] ? [default $2]" 
  else
-   echo "$1 [Y/N] ?" 2>&1
+   Echo "$1 [Y/N] ?" 
  fi
  read ans
  if [ "$ans" = "" ] && [ "$2" != "" ]; then
@@ -63,22 +70,23 @@ while [ $ok -ne 1 ]; do
  fi
  if [ $ok -ne 1 ]; then
   if  [ "$2" != "" ]; then
-   echo "Please, answer Y for Yes or N for No (default means $2) !" 2>&1
+   Echo "Please, answer Y for Yes or N for No (default means $2) !" 
   else
-   echo "Please, answer Y for Yes or N for No !" 2>&1
+   Echo "Please, answer Y for Yes or N for No !" 
   fi
  fi
 done
+echo "(Answer is $ans)" >> $MWSRC/Install.log
 echo ""
 }
 
 Abort()
 {
   cd $CWD
-  echo "***** Abort $_Prog at level $level." 2>&1
+  Echo "***** Abort $_Prog at level $level." 
   if [ -d $MWNEWPUB ]; then
-    echo "***** If you don't plan to continue the installation later using '$_Prog -level $level'," 2>&1
-    echo "***** you should remove $MWNEWPUB." 2>&1 
+    Echo "***** If you don't plan to continue the installation later using '$_Prog -level $level'," 
+    Echo "***** you should remove $MWNEWPUB."
     Answer "***** Remove it now" "Y"
     if [ "$ans" = "Y" ]; then
       rm -rf $MWNEWPUB
@@ -94,7 +102,7 @@ if [ $# -lt 1 ] || [ $# -gt 7 ]; then
 fi
 
 
-CWD=`pwd`
+CWD=`/bin/pwd`
 pubinstall=0
 clear=0
 kernelopt=""
@@ -103,7 +111,6 @@ setenvopt="-privateonly"
 l=1
 level=0
 MWNEWPUB="/void$$"
-NewTrap
 
 while [ "$1" != "" ]
 do
@@ -148,6 +155,15 @@ do
        esac
 done
 
+
+#--------------------------
+echo ==== >> $MWSRC/Install.log
+echo ==== `date`: Run $_Prog Vers $_Vers >> $MWSRC/Install.log
+echo ====  >> $MWSRC/Install.log
+#--------------------------
+
+NewTrap
+
 # Set optimization flag for cmw2 if -g not set
 a=`echo $cmw2opt | grep "\-g"`
 if [ "$a" = "" ]; then
@@ -155,73 +171,78 @@ if [ "$a" = "" ]; then
 fi 
 
 if [ ! -r $MWSRC/VERS ]; then
- echo "***** Cannot find version file in $MWSRC : Are you sure that" 2>&1
- echo "***** $MWSRC is the MegaWave2 Distribution home directory ?" 2>&1
+ Echo "***** Cannot find version file in $MWSRC : Are you sure that" 
+ Echo "***** $MWSRC is the MegaWave2 Distribution home directory ?" 
  Abort
 fi
 
 if [ ! -r $MWSRC/kernel/Install ]; then
- echo "***** Cannot find kernel Install in $MWSRC : Are you sure that" 2>&1
- echo "***** $MWSRC is the MegaWave2 Distribution home directory ?" 2>&1
+ Echo "***** Cannot find kernel Install in $MWSRC : Are you sure that" 
+ Echo "***** $MWSRC is the MegaWave2 Distribution home directory ?"
  Abort
 fi
 
-echo "************************************************************************"
-echo "***** Begin the MegaWave2 Installation Process (cross the fingers) *****"
-echo "************************************************************************"
-echo "***** `date`"
+Echo "************************************************************************"
+Echo "***** Begin the MegaWave2 Installation Process (cross the fingers) *****"
+Echo "************************************************************************"
+Echo "***** `date`"
 
 level=`echo "$level 1 + p" | dc`
 NewTrap
 if [ $l -le $level ]; then 
- echo "*****************************************"
- echo "***** Level $level : Set the environment *****"
- echo "*****************************************"
+ Echo "*****************************************"
+ Echo "***** Level $level : Set the environment *****"
+ Echo "*****************************************"
 
  MWSHELL=$MWSRC/kernel/shell
  if [ ! -x $MWSHELL/mwsetenv ]; then
-   echo "***** Cannot exec $MWSHELL/mwsetenv : Are you sure that" 2>&1
-   echo "***** $MWSRC is the MegaWave2 Distribution home directory ?" 2>&1
+   Echo "***** Cannot exec $MWSHELL/mwsetenv : Are you sure that" 
+   Echo "***** $MWSRC is the MegaWave2 Distribution home directory ?" 
    Abort
  fi
  $MWSHELL/mwsetenv $setenvopt $MWSRC
  if [ $? -ne 0 ]; then
-   echo "***** Error while setting environment !" 2>&1
+   Echo "***** Error while setting environment !"
    Abort
  fi
  MWSHELL=$MWSRC/kernel/shell
  machinetype=`$MWSHELL/mwarch -s`
  MWPROFILE=$MWSRC/sys/lib/$machinetype/.profile_adm_megawave2
  if [ ! -x $MWPROFILE ]; then
-   echo "***** Cannot exec profile $MWPROFILE !" 2>&1
+   Echo "***** Cannot exec profile $MWPROFILE !" 
    Abort
  fi
  . $MWPROFILE
+ if [ $? -ne 0 ]; then
+    Echo "***** Profile $MWPROFILE malformed !" 
+    Abort
+ fi
 
 # end of level
 fi
 
+MWSHELL=$MWSRC/kernel/shell
 if [ $pubinstall -eq 1 ]; then
   if [ "$PUBLIC_MEGAWAVE2" = "$PRIVATE_MEGAWAVE2" ]; then
-    echo "***** Option -public is meaningless since PUBLIC MegaWave2 is the same than PRIVATE." 2>&1
-    echo "***** Please rerun $_Prog with right options or change PUBLIC_MEGAWAVE2 value." 2>&1
+    Echo "***** Option -public is meaningless since PUBLIC MegaWave2 is the same than PRIVATE." 
+    Echo "***** Please rerun $_Prog with right options or change PUBLIC_MEGAWAVE2 value." 
     Abort
   fi
   MWDIRPUB=`dirname $PUBLIC_MEGAWAVE2`
   if [ ! -w $MWDIRPUB ]; then
-    echo "***** You don't have permission to install PUBLIC MegaWave2 on $MWDIRPUB !"
-    echo "***** Are you sure you are the MegaWave2 Administrator ?" 2>&1
+    Echo "***** You don't have permission to install PUBLIC MegaWave2 on $MWDIRPUB !"
+    Echo "***** Are you sure you are the MegaWave2 Administrator ?" 
     Abort
   fi
   if [ $clear -eq 1 ] && [ -d $PUBLIC_MEGAWAVE2 ]; then
     MWORGPUB=$PUBLIC_MEGAWAVE2
     if [ -d $MWORGPUB ] && [ ! -r  $MWORGPUB/VERS ]; then
-      echo "***** Cannot find version file in $MWORGPUB !" 2>&1
-      echo "***** I suppose this PUBLIC MegaWave2 is an obsolete version." 2>&1
+      Echo "***** Cannot find version file in $MWORGPUB !" 
+      Echo "***** I suppose this PUBLIC MegaWave2 is an obsolete version." 
       Answer "***** Ok to rename it ${MWORGPUB}_old and continue the installation" "Y"
       if [ "$ans" = "Y" ]; then
         if [ -d ${MWORGPUB}_old ]; then
-          echo "***** This old directory already exists !"  2>&1
+          Echo "***** This old directory already exists !"  
           Answer "***** Ok to remove it and continue the installation" "Y"
           if [ "$ans" = "Y" ]; then
             rm -rf ${MWORGPUB}_old
@@ -236,6 +257,9 @@ if [ $pubinstall -eq 1 ]; then
     fi
   fi
 fi
+
+# Set default value for newvers
+newvers=`cat $MWSRC/VERS`
 
 # If Install PUBLIC, check if $PUBLIC_MEGAWAVE2 comes from a former incomplete
 # installation. If yes, do not create a temporary directory.
@@ -263,13 +287,13 @@ if [ $pubinstall -ne 1 ] || [ ! -r $PUBLIC_MEGAWAVE2/INSTALL_NOT_COMPLETE ]; the
 
     MWNEWPUB=$MWDIRPUB/MegaWave2_new_V${newvers}
     PUBLIC_MEGAWAVE2=$MWNEWPUB
-    echo "***** Make PUBLIC installation in the temporary directory $PUBLIC_MEGAWAVE2"
+    Echo "***** Make PUBLIC installation in the temporary directory $PUBLIC_MEGAWAVE2"
     if [ -d $PUBLIC_MEGAWAVE2 ] && [ $l -le 1 ]; then
       Answer "***** This directory already exists. May I remove it" "Y"
       if [ "$ans" = "Y" ]; then
         rm -rf $PUBLIC_MEGAWAVE2
       else
-        echo "***** OK, hope you know what you are doing..."       
+        Echo "***** OK, hope you know what you are doing..."       
       fi              
     fi
   else
@@ -299,14 +323,14 @@ fi
 level=`echo "$level 1 + p" | dc`
 NewTrap
 if [ $l -le $level ]; then 
- echo "****************************************"
- echo "***** Level $level : Compile the kernel *****"
- echo "*****************************************"
+ Echo "****************************************"
+ Echo "***** Level $level : Compile the kernel *****"
+ Echo "*****************************************"
 
  cd kernel; 
  ./Install $kernelopt
  if [ $? -ne 0 ]; then
-   echo "***** Error while compiling kernel !" 2>&1
+   Echo "***** Error while compiling kernel !" 
    Abort
  fi
 # end of level
@@ -315,15 +339,31 @@ fi
 level=`echo "$level 1 + p" | dc`
 NewTrap
 if [ $l -le $level ]; then 
- echo "*****************************************"
- echo "***** Level $level : Compile the modules *****"
- echo "*****************************************"
+ Echo "*****************************************"
+ Echo "***** Level $level : Compile the modules *****"
+ Echo "*****************************************"
+
+# Check if cmw2 works well. If not, output error message from cmw2
+# so the user can guess what is happening.
+ 
+ mwcmwcheck
+ if [ $? -ne 0 ]; then
+   Echo "***** Modules cannot be compiled ! It means something went wrong during the kernel installation stage..." 
+   Abort
+ fi
+
+# Now, compile all modules.
 
  cd $MWSRC
  cmw2_all $cmw2opt src
  if [ $? -ne 0 ]; then
-   echo "***** Error while compiling modules !" 2>&1
-   Abort
+   Echo "***** Error while compiling modules !" 
+   Answer "***** Some module(s) could not be successfully compiled ! Abort the installation" "Y"
+   if [ "$ans" = "Y" ]; then
+    Abort       
+   else
+    Echo "***** I continue, but remember that some module(s) won't be available..."       
+   fi 
  fi
 # end of level
 fi
@@ -331,24 +371,32 @@ fi
 level=`echo "$level 1 + p" | dc`
 NewTrap
 if [ $l -le $level ]; then 
- echo "*******************************************************"
- echo "***** Level $level : Compile the documentation (guid3) *****"
- echo "*******************************************************"
+ Echo "*******************************************************"
+ Echo "***** Level $level : Compile the documentation (guid3) *****"
+ Echo "*******************************************************"
 
  mwdep -adm
  if [ $? -ne 0 ]; then
-   echo "***** Error while making dependencies list ! I continue but" 2>&1
-   echo "***** you will not get modules dependencies in the documentation." 2>&1
+   Echo "***** Error while making dependencies list ! I continue but" 
+   Echo "***** you will not get modules dependencies in the documentation."
  fi
- make_mw2doc $MWSRC
+ mwmakedoc $MWSRC
  if [ $? -ne 0 ]; then
-   echo "***** Error while making documentation !" 2>&1
+   Echo "***** Error while making documentation !" 
    Abort
  fi
  cd $MWSRC/doc
- latex guid3
- latex guid3
- latex guid3
+ latex guid3.tex
+# Check whether or not makeindex has to be called
+ package=`grep "\\usepackage{makeidx}" guid3.tex`
+ if [ "$package" = "\\usepackage{makeidx}" ] && [ -r guid3.idx ]; then
+    makeindex=`which makeindex`
+    if [ "$makeindex" != "" ] && [ -x $makeindex ]; then
+      makeindex guid3.idx
+  fi
+ fi
+ latex guid3.tex
+ latex guid3.tex
 # end of level
 fi
 
@@ -363,26 +411,26 @@ fi
 level=`echo "$level 1 + p" | dc`
 NewTrap
 if [ $l -le $level ] && [ $pubinstall -eq 1 ]; then
-  echo "*********************************************"
-  echo "***** Level $level : Install PUBLIC modules  *****"
-  echo "*********************************************"
+  Echo "*********************************************"
+  Echo "***** Level $level : Install PUBLIC modules  *****"
+  Echo "*********************************************"
 
   if [ ! -d $PUBLIC_MEGAWAVE2 ]; then
-    echo "***** Cannot find previous temporary PUBLIC installation" 2>&1
-    echo "***** in $PUBLIC_MEGAWAVE2 !" 2>&1
-    echo "***** You have to rerun $_Prog from level 1." 2>&1
+    Echo "***** Cannot find previous temporary PUBLIC installation" 
+    Echo "***** in $PUBLIC_MEGAWAVE2 !" 
+    Echo "***** You have to rerun $_Prog from level 1." 
     Abort
   fi
 
 # Make the MODULES file
   mwmodlist -mfile $MWSRC > $MWSRC/MODULES.${MW_MACHINETYPE}
   if [ $? -ne 0 ]; then
-    echo "***** Cannot generate MODULES file on ${MW_MACHINETYPE} !" 2>&1
+    Echo "***** Cannot generate MODULES file on ${MW_MACHINETYPE} !" 
     Abort
   fi
   mwmodinstall $MWSRC/MODULES.${MW_MACHINETYPE}
   if [ $? -ne 0 ]; then
-    echo "***** Cannot install PUBLIC modules !" 2>&1
+    Echo "***** Cannot install PUBLIC modules !" 
     Abort
   fi
 # end of level
@@ -391,14 +439,14 @@ fi
 level=`echo "$level 1 + p" | dc`
 NewTrap
 if [ $l -le $level ] && [ $pubinstall -eq 1 ]; then
-  echo "**************************************************"
-  echo "***** Level $level : Install miscellaneous files  *****"
-  echo "**************************************************"
+  Echo "**************************************************"
+  Echo "***** Level $level : Install miscellaneous files  *****"
+  Echo "**************************************************"
 
   if [ ! -d $PUBLIC_MEGAWAVE2 ]; then
-    echo "***** Cannot find previous temporary PUBLIC installation" 2>&1
-    echo "***** in $PUBLIC_MEGAWAVE2 !" 2>&1
-    echo "***** You have to rerun $_Prog from level 1." 2>&1
+    Echo "***** Cannot find previous temporary PUBLIC installation" 
+    Echo "***** in $PUBLIC_MEGAWAVE2 !" 
+    Echo "***** You have to rerun $_Prog from level 1." 
     Abort
   fi
 
@@ -497,24 +545,24 @@ fi
 level=`echo "$level 1 + p" | dc`
 NewTrap
 if [ -d $MWNEWPUB ]; then
-  echo "*****************************************************************"
-  echo "***** Level $level : Make changes in effect in PUBLIC MegaWave2  *****"
-  echo "*****************************************************************"
+  Echo "*****************************************************************"
+  Echo "***** Level $level : Make changes in effect in PUBLIC MegaWave2  *****"
+  Echo "*****************************************************************"
   mv -f $MWORGPUB $MWDIRPUB/MegaWave2_V${oldvers}
   if [ $? -ne 0 ]; then
-    echo "***** Cannot rename $MWORGPUB !" 2>&1
+    Echo "***** Cannot rename $MWORGPUB ! ($MWORGPUB ->  $MWDIRPUB/MegaWave2_V${oldvers})" 
     Abort
   fi
   mv -f $PUBLIC_MEGAWAVE2 $MWORGPUB
   if [ $? -ne 0 ]; then
-    echo "***** Cannot rename $PUBLIC_MEGAWAVE2 !" 2>&1
+    Echo "***** Cannot rename $PUBLIC_MEGAWAVE2 ! ($MWORGPUB -> $PUBLIC_MEGAWAVE2)" 
     Abort
   fi
   chmod 755 $MWORGPUB
   echo $newvers > $MWORGPUB/VERS
   chmod 644 $MWORGPUB/VERS
-  echo "***** Now, users should experiment in $MWORGPUB the new PUBLIC version $newvers"
-  echo "***** They still may get the old PUBLIC version $oldvers in $MWDIRPUB/MegaWave2_V${oldvers}"
+  Echo "***** Now, users should experiment in $MWORGPUB the new PUBLIC version $newvers"
+  Echo "***** They still may get the old PUBLIC version $oldvers in $MWDIRPUB/MegaWave2_V${oldvers}"
   PUBLIC_MEGAWAVE2=$MWORGPUB
 fi
 
@@ -522,11 +570,24 @@ if [ $pubinstall -eq 1 ]; then
   rm -f $PUBLIC_MEGAWAVE2/INSTALL_NOT_COMPLETE
 fi
 cd $CWD
-echo " "
-echo "***** `date`"
-echo "*******************************************************************"
-echo "***** Install done for MegaWave2 ! (Leave your fingers quiet) *****"
-echo "*******************************************************************"
+Echo " "
+Echo "***** `date`"
+Echo "*******************************************************************"
+Echo "***** Install done for MegaWave2 ! (Leave your fingers quiet) *****"
+Echo "*******************************************************************"
+Echo " "
+
+# After installation done, optional checking of modules
+trap "Echo '***** Checking of modules aborted'; exit 1" 2 3
+chk=`mwwhere -bin Checkmodules`
+if [ "$chk" != "" ]; then
+  Answer "***** Do you want to check the module library" "N"
+  if [ "$ans" = "Y" ]; then
+    MW_CHECK_HIDDEN=1
+    export MW_CHECK_HIDDEN
+    Checkmodules
+  fi
+fi
 
 exit 0
 
