megawave-2.20 import
downloaded on 2009-02-27 from
http://megawave.cmla.ens-cachan.fr/distribution/MegaWave2_V2.20.tar.gz

diff --git a/kernel/shell/cmw2 b/kernel/shell/cmw2
--- a/kernel/shell/cmw2
+++ b/kernel/shell/cmw2
@@ -2,8 +2,8 @@
 #--------------------------- Shell MegaWave2 Macro --------------------------#
 _sccsid="%Z%MegaWave2 %R%, %M% %I%, %G%";
 _Prog="`basename $0`"
-_Vers="1.47"
-_Date="2002"
+_Vers="1.49"
+_Date="2003"
 _Func="Compile a MegaWave2 Module or Macro";
 _Auth="Jacques Froment, Sylvain Parrino";
 _Usage=" [-gnu] [-g] [-X] [-O] [-v] [-c compiler_option] [-Dname[=def]] [-Uname] [-Ipathname] [-w] [-Ldirectory] [-llibrary] [-dep] [-pubsyslib] [-N] module"
@@ -15,6 +15,21 @@ _Usage=" [-gnu] [-g] [-X] [-O] [-v] [-c compiler_option] [-Dname[=def]] [-Uname]
 # CMLA, Ecole Normale Superieure de Cachan, 61 av. du President Wilson,
 #       94235 Cachan cedex, France. Email: megawave@cmla.ens-cachan.fr 
 #-----------------------------------------------------------------------------
+
+ChooseTMP()
+
+{
+if  [ "$TMP" = ""  ] || [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+ TMP=/usr/tmp
+ if  [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+  TMP=/tmp
+  if  [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+   echo "$_Prog : Fatal Error : cannot choose TMP !"
+   exit 1
+  fi
+ fi
+fi
+}
 
 # Remove given file(s) if verbose flag not set; if set, output file name.
 
@@ -73,10 +88,7 @@ trap "echo quit; exit 1" 3
 
 # Defaults
 MWDIR=$HOME/megawave2
-TMP=/usr/tmp
-if  [ ! -w $TMP ]; then
-  TMP=/tmp
-fi
+ChooseTMP
 
 # C Compiler
 CC=cc
@@ -144,7 +156,7 @@ if [ "$dir" = "" ]; then
   ULIB=$ADM_LIBMW
   XULIB=$XADM_LIBMW
   macropt="-adm"
-  echo "Warning: the target user is the system on $MWDESTDIR"
+  echo "Beware, the target user is the system on $MWDESTDIR"
  fi
 else
 # user mode
@@ -277,12 +289,12 @@ do
    # XMegaWave extension
     -X)         XMW=1
     		if [ ! -f $MWDIR/sys/include/XMW2.h ]; then 
-    		 echo "Warning: option -X cannot be activated (No XMegaWave2 include file)"
+    		 echo "WARNING: option -X cannot be activated (No XMegaWave2 include file)"
     		 XMW=0
     		else
     		 if [ ! -f /usr/include/Xm/Xm.h ] && \
 			[ ! -f ${MW_INCLUDEXm}/Xm/Xm.h ]; then
-    		  echo "Warning: option -X cannot be activated (No Motif include file)"
+    		  echo "WARNING: option -X cannot be activated (No Motif include file)"
     		  XMW=0
       		 fi
       		fi
@@ -299,11 +311,11 @@ do
     # Objects file
     *.o)	OBJ="$OBJ $1"
 		;;
-    # MegaWave 2 module 
+    # MegaWave2 module 
     *.$EXT)	MWFILE=$1
 		STOP="TRUE"
 		;;
-    # MegaWave 2 module without extension
+    # MegaWave2 module without extension
     [!-]*)	if  [ -f $1.$EXT ]; then
                   # It is a module
  		  MWFILE=$1.$EXT
@@ -570,12 +582,12 @@ else
     echo "done."
   fi
 
-  # Teste si nouvelle commande ou non
-  if [ -x $MWDESTDIR/bin/$MW_MACHINETYPE/$MODULE ] || \
-     [ -x $MWDESTDIR/bin/$MW_MACHINETYPE/$MODULE.old ]; then
-     NEW=0;
+  # Check whether or not this is a new MegaWave2 module
+  if [ -x $MWDESTDIR/bin/$MW_MACHINETYPE/$MODULE ]; then
+     NEW_MODULE=0;
   else
-     NEW=1;
+     NEW_MODULE=1;
+     current=`which $MODULE 2> /dev/null`
   fi
 
   # Recherche des librairies 
@@ -661,8 +673,12 @@ else
 #     echo "          striping the command"
      strip $MWDESTDIR/bin/$MW_MACHINETYPE/$MODULE
     fi
-    if  [ $NEW -eq 1 ]; then
-       echo "     (New command added)"
+    if  [ $NEW_MODULE -eq 1 ]; then
+       echo "     New MegaWave2 command added !"
+       if [ "$current" != "" ] && [ -x $current ]; then
+       echo "     WARNING : same name than command '$current' ! One will be hidden..."
+       fi
+
     fi
   fi
 
diff --git a/kernel/shell/cmw2_all b/kernel/shell/cmw2_all
--- a/kernel/shell/cmw2_all
+++ b/kernel/shell/cmw2_all
@@ -2,11 +2,11 @@
 #--------------------------- Shell MegaWave Macro ----------------------------#
 _sccsid="%Z%MegaWave2 %R%, %M% %I%, %G%";
 _Prog="`basename $0`"
-_Vers="1.22";
-_Date="1999-2002";
+_Vers="1.26";
+_Date="1999-2003";
 _Func="Compile all MegaWave2 modules and user's macros, recursively on each subdirectory";
 _Auth="Jacques Froment";
-_Usage="[-gnu] [-clear] [-g] [-X] [-O] [-c compiler_option] [-Dname[=def]] [-Uname] [-Ipathname] [-w] [-Ldirectory] [-llibrary] [-2p] [-sp] [-dep] [-pubsyslib] [-force] [-N processid] group_directory"
+_Usage="[-gnu] [-clear] [-g] [-X] [-O] [-c compiler_option] [-Dname[=def]] [-Uname] [-Ipathname] [-w] [-Ldirectory] [-llibrary] [-2p] [-sp] [-dep] [-pubsyslib] [-force] [-v tracefile] [-N processid] group_directory"
 
 #----------------------------------------------------------------------------#
 # This file is part of the MegaWave2 system macros. 
@@ -16,6 +16,42 @@ _Usage="[-gnu] [-clear] [-g] [-X] [-O] [-c compiler_option] [-Dname[=def]] [-Una
 # CMLA, Ecole Normale Superieure de Cachan, 61 av. du President Wilson,
 #       94235 Cachan cedex, France. Email: megawave@cmla.ens-cachan.fr 
 #-----------------------------------------------------------------------------
+
+# Remove all old temporary files that have been generated by cmw2,
+# so that no confusion can be made.
+
+RemoveTMPfiles()
+
+{
+ if  [ "$TMP" != ""  ] && [ -d $TMP ] &&  [ -w $TMP ]; then
+  for f in `find ${TMP}/. -name "mw*" -ctime +1 -type f -print`
+  do
+   /bin/rm -f $f > /dev/null 2>&1
+  done
+ fi
+}
+
+ChooseTMP()
+
+{
+if  [ "$TMP" = ""  ] || [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+ TMP=/usr/tmp
+ if  [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+  TMP=/tmp
+  if  [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+   echo "$_Prog : Fatal Error : cannot choose TMP !"
+   exit 1
+  fi
+ fi
+fi
+}
+
+Echo()
+
+{
+ echo "$1"
+ echo "$1" >> $trace
+}
 
 if [ "${MW_MACHINETYPE}" = "" ]; then
    echo "Please set the \$MW_MACHINETYPE environment variable" 1>&2
@@ -45,7 +81,11 @@ firstpass=""
 # -sp if second-pass
 secondpass=""
 
+# trace file. By default, /dev/null : no trace
+trace="/dev/null"
+
 cmw_opt=""
+cmw_all_opt=""
 
 while [ "$1" != "" ]
 do
@@ -59,7 +99,12 @@ do
                shift
                ;;
 
-	       
+    "-v")      shift
+	       trace=$1
+	       shift
+	       cmw_all_opt="$cmw_all_opt -v $trace"    
+               ;;
+
     "-2p")  twopass=1
 	    shift
             ;;
@@ -72,15 +117,18 @@ do
 	    shift
             ;;
 
-    "-dep") cmw_opt="$cmw_opt -dep"
+    "-dep") cmw_all_opt="$cmw_all_opt -dep"
+	    cmw_opt="$cmw_opt -dep"
             shift
             ;;
 
-    "-pubsyslib") cmw_opt="$cmw_opt -pubsyslib"
-            shift
-            ;;
+    "-pubsyslib") cmw_all_opt="$cmw_all_opt -pubsyslib"
+		  cmw_opt="$cmw_opt -pubsyslib"
+		  shift
+		  ;;
 
      -c)	shift
+		cmw_all_opt="$cmw_all_opt -c $1"
 		cmw_opt="$cmw_opt -c $1"
 		shift
 		;;
@@ -92,35 +140,43 @@ do
           ;;
 
           
-    -g)   cmw_opt="$cmw_opt -g";
+    -g)   cmw_all_opt="$cmw_all_opt -g";
+	  cmw_opt="$cmw_opt -g";
           shift;
           ;;
 
-    -gnu)	cmw_opt="$cmw_opt -gnu"
+    -gnu)	cmw_all_opt="$cmw_all_opt -gnu"
+		cmw_opt="$cmw_opt -gnu"
     		shift
 		;;
 		
-    -X)         cmw_opt="$cmw_opt -X"
+    -X)         cmw_all_opt="$cmw_all_opt -X"
+		cmw_opt="$cmw_opt -X"
     		shift
     		;;
 
-    -O*)        cmw_opt="$cmw_opt $1"
+    -O*)        cmw_all_opt="$cmw_all_opt $1"
+		cmw_opt="$cmw_opt $1"
     		shift
     		;;
 
-    -D*|-I*|-U*) cmw_opt="$cmw_opt $1"
-                shift
-		;;
+    -D*|-I*|-U*) cmw_all_opt="$cmw_all_opt $1"
+		 cmw_opt="$cmw_opt $1"
+                 shift
+		 ;;
 
-    -w)         cmw_opt="$cmw_opt $1"
+    -w)         cmw_all_opt="$cmw_all_opt $1"
+		cmw_opt="$cmw_opt $1"
 		shift
 		;;
 
-    -L*)	cmw_opt="$cmw_opt $1"
+    -L*)	cmw_all_opt="$cmw_all_opt $1"
+		cmw_opt="$cmw_opt $1"
 		shift
 		;;
 
-    -l*)	cmw_opt="$cmw_opt $1"
+    -l*)	cmw_all_opt="$cmw_all_opt $1"
+		cmw_opt="$cmw_opt $1"
 		shift
 		;;
 
@@ -161,14 +217,15 @@ else
   fi
 fi
 
-TMP=/usr/tmp
-if  [ ! -w $TMP ]; then
-  TMP=/tmp
-fi
+ChooseTMP
 
 if [ "$NoDisplay" != "yes" ]; then
 
 # First entry for this command
+
+ if [ "$trace" != "/dev/null" ] && [ -f $trace ]; then
+  /bin/rm -f $trace > /dev/null
+ fi
 
  if [ "$MWDESTDIR" = "$MEGAWAVE2" ] && [ $force -eq 0 ]; then
    echo "Warning: you will modify the system files on $MWDESTDIR"
@@ -222,19 +279,23 @@ if [ "$NoDisplay" != "yes" ]; then
    read a
    if [ "$a" = "y" ] || [ "$a" = "Y" ]; then
      echo "Removing..."
-     rm -rf $arep
+     /bin/rm -rf $arep
    else
      echo "Cannot continue."
      exit 1
    fi
   else
     if [ "$arep" != "" ]; then
-      rm -rf $arep
+      /bin/rm -rf $arep
     fi
   fi
 
 # End clear
  fi
+
+# Remove all old temporary files that have been generated by cmw2,
+# so that no confusion can be made.
+RemoveTMPfiles
 
 processid=$$
 errorfile=$TMP/cmw2_all_${processid}.error
@@ -243,12 +304,12 @@ echo "List of unsuccessful compilations :" > $errorfile
 echo "--------------------------------- " >> $errorfile
 echo '' >> $errorfile
 
-echo ''
-echo "          ----------------------------"
-echo "               Generic MegaWave2 "
-echo "          Commands Package Compilation"
-echo "          ----------------------------"
-echo ''
+Echo ''
+Echo "          ----------------------------"
+Echo "               Generic MegaWave2 "
+Echo "          Commands Package Compilation"
+Echo "          ----------------------------"
+Echo ''
 mwechon "------ Beginning at "
 date
 echo ''
@@ -258,31 +319,29 @@ fi
 
 errorfile=$TMP/cmw2_all_${processid}.error
 erroroccured=$TMP/cmw2_all_${processid}.erroroccured
-stdout=$TMP/cmw2_all_${processid}.stdout
-stderr=$TMP/cmw2_all_${processid}.stderr
 
 # trap
-trap "echo interrupt; /bin/rm -f $errorfile $erroroccured $stdout; exit 1" 2
-trap "echo quit; /bin/rm -f $errorfile $erroroccured $stderr; exit 1" 3
+trap "echo Interrupt; /bin/rm -f $errorfile $erroroccured; exit 1" 2
+trap "echo Quit; /bin/rm -f $errorfile $erroroccured ; exit 1" 3
 
 if [ $twopass = 1 ]; then
   echo '' >> $errorfile
   echo 'First pass:' >> $errorfile
   echo '' >> $errorfile
-  echo ' '
-  echo '-----------------------'
-  echo 'Beginning First pass...'
-  echo '-----------------------'
-  echo ' '
-  cmw2_all $cmw_opt -fp -N $processid ${dir}
+  Echo ' '
+  Echo '-----------------------'
+  Echo 'Beginning First pass...'
+  Echo '-----------------------'
+  Echo ' '
+  cmw2_all $cmw_all_opt -fp -N $processid ${dir}
   echo '' >> $errorfile
   echo 'Second pass:' >> $errorfile
   echo '' >> $errorfile
-  echo ' '
-  echo '------------------------'
-  echo 'Beginning Second pass...'
-  echo '------------------------'
-  echo ' '
+  Echo ' '
+  Echo '------------------------'
+  Echo 'Beginning Second pass...'
+  Echo '------------------------'
+  Echo ' '
   secondpass="-sp"
 fi
 
@@ -291,9 +350,9 @@ do
   if [ ! -d ${dir}/${file} ]; then
     if [ "$secondpass" != "-sp" ] || 
 	[ ! -x $MWDESTDIR/bin/$MW_MACHINETYPE/`basename $file .c` ]; then 
-	mwechon "$file "
-        (cd ${dir}; cmw2 -N $cmw_opt $file 1>> $stdout 2>> $stderr;)
-	retcmw=$?
+        mwechon "$file "
+        (cd ${dir}; cmw2 -N $cmw_opt $file 1>> $trace 2>&1;)
+        retcmw=$?
 	if [ $retcmw -ne 0 ]; then
          echo "${dir}/${file}" >> $errorfile
 # retcmw = 2 : error due to failed link (unknown reference)
@@ -306,10 +365,10 @@ do
 	fi
     fi
   else
-   echo "---> Scan Subdirectory ${dir}/${file} <---"
-   cmw2_all $cmw_opt $firstpass $secondpass -N $processid ${dir}/${file}
-   echo ''
-   echo ''
+   Echo "---> Scan Subdirectory ${dir}/${file} <---"
+   cmw2_all $cmw_all_opt $firstpass $secondpass -N $processid ${dir}/${file}
+   Echo ''
+   Echo ''
   fi
 done
 
@@ -322,13 +381,14 @@ if [ "$NoDisplay" != "yes" ]; then
 
  if [ -f $erroroccured ]; then
   cat $errorfile
-  echo ''
-  rm -f $errorfile $erroroccured $stdout $stderr
+  cat $errorfile >> $trace
+  Echo ''
+  rm -f $errorfile $erroroccured
   exit 1
  else
-  echo "All modules were successfully compiled !"
-  echo ''
-  rm -f $errorfile $stdout $stderr
+  Echo "All modules were successfully compiled !"
+  Echo ''
+  rm -f $errorfile $erroroccured
   exit 0
  fi
 fi
diff --git a/kernel/shell/cxmw2debug b/kernel/shell/cxmw2debug
--- a/kernel/shell/cxmw2debug
+++ b/kernel/shell/cxmw2debug
@@ -2,8 +2,8 @@
 #--------------------------- Shell MegaWave2 Macro --------------------------#
 _sccsid="%Z%MegaWave2 %R%, %M% %I%, %G%";
 _Prog="`basename $0`"
-_Vers="1.06"
-_Date="1997-2002"
+_Vers="1.07"
+_Date="1997-2003"
 _Func="Compile your own XMegaWave2 software (debug-mode)";
 _Auth="Jacques Froment";
 _Usage="[-gnu] [-Dname[=def]] [-Uname] [-Ipathname] [-w] [-Ldirectory] [-llibrary] [-pubsyslib] modules_file"
@@ -15,6 +15,21 @@ _Usage="[-gnu] [-Dname[=def]] [-Uname] [-Ipathname] [-w] [-Ldirectory] [-llibrar
 # CMLA, Ecole Normale Superieure de Cachan, 61 av. du President Wilson,
 #       94235 Cachan cedex, France. Email: megawave@cmla.ens-cachan.fr 
 #-----------------------------------------------------------------------------
+
+ChooseTMP()
+
+{
+if  [ "$TMP" = ""  ] || [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+ TMP=/usr/tmp
+ if  [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+  TMP=/tmp
+  if  [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+   echo "$_Prog : Fatal Error : cannot choose TMP !"
+   exit 1
+  fi
+ fi
+fi
+}
 
 if [ "${MW_MACHINETYPE}" = "" ]; then
    echo "Please set the \$MW_MACHINETYPE environment variable"
@@ -33,11 +48,7 @@ fi
 trap "echo interrupt; exit 1" 2
 trap "echo quit; exit 1" 3
 
-# TMP Directory
-TMP=/usr/tmp
-if [ "$TMPDIR" != "" ]; then
-  TMP=$TMPDIR
-fi
+ChooseTMP
 
 # XMegaWave2 executable name
 XMW2=myxmw2
diff --git a/kernel/shell/mwdoc b/kernel/shell/mwdoc
--- a/kernel/shell/mwdoc
+++ b/kernel/shell/mwdoc
@@ -2,11 +2,11 @@
 #--------------------------- Shell MegaWave Macro ----------------------------#
 _sccsid="%Z%MegaWave2 %R%, %M% %I%, %G%";
 _Prog="mwdoc"
-_Vers="1.04";
-_Date="1999-2002";
+_Vers="1.05";
+_Date="1999-2003";
 _Func="Enter the MegaWave2 documentation";
 _Auth="Jacques Froment";
-_Usage="[<name> || M || S || 1 || 2 || 3]"
+_Usage="[<name> || M || S || F || 1 || 2 || 3]"
 #----------------------------------------------------------------------------#
 # This file is part of the MegaWave2 system macros. 
 # MegaWave2 is a "soft-publication" for the scientific community. It has
@@ -16,16 +16,17 @@ _Usage="[<name> || M || S || 1 || 2 || 3]"
 #       94235 Cachan cedex, France. Email: megawave@cmla.ens-cachan.fr 
 #-----------------------------------------------------------------------------
 
-if [ $# -ne 1 ]; then
+if [ $# -lt 1 ]; then
  echo " "
  echo "> Type the MegaWave2 documentation you want to display <"
  echo " "
- echo "<name> : name of a module or of a user's macro"
- echo "M      : list all Modules and user's Macros"
- echo "S      : list all System's macros"
- echo "1      : Vol.1  User's Guide"
- echo "2      : Vol.2  System Library"
- echo "3      : Vol.3  User's Modules and Macros Library"
+ echo "<name>      : name of a module or of a user's macro"
+ echo "M           : list all Modules and user's Macros"
+ echo "S           : list all System's macros"
+ echo "F           : list and describe available external (File) types"
+ echo "1           : Vol.1  User's Guide"
+ echo "2           : Vol.2  System Library"
+ echo "3           : Vol.3  User's Modules and Macros Library"
  echo " "
  mwechon ">"
  read X
@@ -67,6 +68,36 @@ if [ "$X" = "s" ] || [ "$X" = "S" ]; then
   mwsysmaclist
   exit 0
 fi
+
+if [ "$X" = "f" ] || [ "$X" = "F" ]; then
+# Select one executable module to call it with -ftypelist
+  onemod=`ls -1 ${MEGAWAVE2}/bin/${MW_MACHINETYPE}  2> /dev/null`
+  if [ $? -ne 0 ]; then
+   echo "Error : no modules compiled or bad directory ${MEGAWAVE2}/bin/${MW_MACHINETYPE} !"
+   exit 1
+  fi
+  onemod=`echo $onemod | cut -f 1 -d " "`
+  if [ "$onemod" = "" ]; then
+   echo "Error : cannot found any executable module !"
+   exit 1
+  fi
+  echo "What kind of file type(s) are you looking for ? Please enter a keyword"
+  mwechon "(you may use regular expression, <return> for all file types) : "
+  read A
+  echo ""
+  echo "File type        Description"
+  echo "---------        -----------"
+  echo ""
+  $onemod -ftypelist | grep -i -e "$A" 2> /dev/null
+  if [ $? -eq 1 ]; then
+   echo "No file type found that matches this keyword !"
+  fi
+  echo ""  
+  echo "You may find more information about file types by reading"
+  echo "the guide Vol.2 System Library (type 'mwdoc 2' to get it)."
+  exit 0
+fi
+
 
 tmod=${X}.tex
 # Defaults
diff --git a/kernel/shell/mwinstall b/kernel/shell/mwinstall
--- a/kernel/shell/mwinstall
+++ b/kernel/shell/mwinstall
@@ -3,8 +3,8 @@
 _sccsid="%Z%MegaWave %R%, %M% %I%, %G%";
 _Func="Install a new MegaWave2 full version (adm only)";
 _Prog="`basename $0`"
-_Vers="1.14"
-_Date="1999-2002"
+_Vers="1.19"
+_Date="1999-2003"
 _Auth="Jacques Froment";
 _Usage="[-static] [-public || -public=private] [-clear] [-debug] [-level l] mw2distribution"
 #-----------------------------------------------------------------------------
@@ -30,6 +30,21 @@ _Usage="[-static] [-public || -public=private] [-clear] [-debug] [-level l] mw2d
 # -debug : Produce debugging information (default : optimize the code).
 # -level l : Install levels greater or equal than l only.
 #-----------------------------------------------------------------------------
+
+ChooseTMP()
+
+{
+if  [ "$TMP" = ""  ] || [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+ TMP=/usr/tmp
+ if  [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+  TMP=/tmp
+  if  [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+   echo "$_Prog : Fatal Error : cannot choose TMP !"
+   exit 1
+  fi
+ fi
+fi
+}
 
 Echo()
 
@@ -106,7 +121,11 @@ CWD=`/bin/pwd`
 pubinstall=0
 clear=0
 kernelopt=""
-cmw2opt="-2p -dep -force"
+
+ChooseTMP
+cmw2trace=${TMP}/cmw2_all$$.trace
+cmw2opt="-2p -dep -force -v $cmw2trace"
+
 setenvopt="-privateonly"
 l=1
 level=0
@@ -264,7 +283,8 @@ newvers=`cat $MWSRC/VERS`
 # If Install PUBLIC, check if $PUBLIC_MEGAWAVE2 comes from a former incomplete
 # installation. If yes, do not create a temporary directory.
 
-if [ $pubinstall -ne 1 ] || [ ! -r $PUBLIC_MEGAWAVE2/INSTALL_NOT_COMPLETE ]; then
+#if [ $pubinstall -ne 1 ] || [ ! -r $PUBLIC_MEGAWAVE2/INSTALL_NOT_COMPLETE ]; then
+if [ $pubinstall -eq 1 ] && [ ! -r $PUBLIC_MEGAWAVE2/INSTALL_NOT_COMPLETE ]; then
 
 # If Install PUBLIC with clear option selected, it means that users may
 # use current version of PUBLIC_MEGAWAVE2 : make the installation in a
@@ -279,7 +299,7 @@ if [ $pubinstall -ne 1 ] || [ ! -r $PUBLIC_MEGAWAVE2/INSTALL_NOT_COMPLETE ]; the
     oldvers=`cat $MWORGPUB/VERS`
     mmoldvers=`echo $oldvers | cut -f 1-2 -d "."`
     mmsrcvers=`cat $MWSRC/VERS | cut -f 1-2 -d "."`
-    if [ "$mmoldvers" = "mmsrcvers" ]; then
+    if [ "$mmoldvers" = "$mmsrcvers" ]; then
       newvers=`$MWSHELL/mwincvers $MWORGPUB`
     else
       newvers=`$MWSHELL/mwincvers $MWSRC`
@@ -327,7 +347,7 @@ if [ $l -le $level ]; then
  Echo "***** Level $level : Compile the kernel *****"
  Echo "*****************************************"
 
- cd kernel; 
+ cd $CWD/kernel; 
  ./Install $kernelopt
  if [ $? -ne 0 ]; then
    Echo "***** Error while compiling kernel !" 
@@ -355,9 +375,16 @@ if [ $l -le $level ]; then
 # Now, compile all modules.
 
  cd $MWSRC
- cmw2_all $cmw2opt src
+ cmw2_all $cmw2opt $MWSRC/src
+
  if [ $? -ne 0 ]; then
    Echo "***** Error while compiling modules !" 
+   if [ -f $cmw2trace ]; then
+    echo "***** To see why errors occurred, here is the content of '$cmw2trace' trace file :" >> $MWSRC/Install.log
+    cat $cmw2trace >> $MWSRC/Install.log
+    rm -f $cmw2trace > /dev/null
+    echo "***** End of content of trace file" >> $MWSRC/Install.log
+   fi  
    Answer "***** Some module(s) could not be successfully compiled ! Abort the installation" "Y"
    if [ "$ans" = "Y" ]; then
     Abort       
@@ -365,6 +392,10 @@ if [ $l -le $level ]; then
     Echo "***** I continue, but remember that some module(s) won't be available..."       
    fi 
  fi
+
+# Remove trace file
+ rm -f $cmw2trace > /dev/null
+
 # end of level
 fi
 
diff --git a/kernel/shell/mwrnwordmod b/kernel/shell/mwrnwordmod
--- a/kernel/shell/mwrnwordmod
+++ b/kernel/shell/mwrnwordmod
@@ -3,8 +3,8 @@
 _sccsid="%Z%MegaWave %R%, %M% %I%, %G%";
 _Prog="mwrnwordmod"
 _Func="Rename words (e.g. system functions or structure fields) inside modules for which name has changed"
-_Vers="1.0"
-_Date="2002"
+_Vers="1.01"
+_Date="2002-03"
 _Auth="Jacques Froment";
 _Usage="[-adm] [-all] [-check] [-d dir] [-f file_of_names]"
 # -adm : administrator : scan $MEGAWAVE2/src directory instead of $MY_MEGAWAVE2/src
@@ -21,6 +21,21 @@ _Usage="[-adm] [-all] [-check] [-d dir] [-f file_of_names]"
 # CMLA, Ecole Normale Superieure de Cachan, 61 av. du President Wilson,
 #       94235 Cachan cedex, France. Email: megawave@cmla.ens-cachan.fr 
 #-----------------------------------------------------------------------------
+
+ChooseTMP()
+
+{
+if  [ "$TMP" = ""  ] || [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+ TMP=/usr/tmp
+ if  [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+  TMP=/tmp
+  if  [ ! -d $TMP ] ||  [ ! -w $TMP ]; then
+   echo "$_Prog : Fatal Error : cannot choose TMP !"
+   exit 1
+  fi
+ fi
+fi
+}
 
 #------------------
 Answer()
@@ -187,10 +202,7 @@ if [ ! -f $fname ]; then
   exit 1
 fi
 
-TMP=/usr/tmp
-if  [ ! -w $TMP ]; then
-  TMP=/tmp
-fi
+ChooseTMP
 
 # new trap
 trap "echo 'interrupt !'; rm -f $TMP/mwrnwordmod_$$_*; exit 1" 2
