megawave-3.01 import
downloaded on 2009-02-27 from
http://megawave.cmla.ens-cachan.fr/distribution/MegaWave2_V3.01.tar.gz

diff --git a/kernel/Install b/kernel/Install
--- a/kernel/Install
+++ b/kernel/Install
@@ -3,8 +3,8 @@
 _sccsid="%Z%MegaWave %R%, %M% %I%, %G%";
 _Func="Install a new version of the MegaWave2 kernel";
 _Prog="`basename $0`"
-_Vers="1.0"
-_Date="1999-2003"
+_Vers="1.3"
+_Date="1999-2007"
 _Auth="Jacques Froment";
 _Usage="[-static] [-public] [-clear] [-debug]"
 #-----------------------------------------------------------------------------
@@ -25,6 +25,22 @@ _Usage="[-static] [-public] [-clear] [-debug]"
 #           addition to the PRIVATE version of MegaWave2.
 # -clear : clear previous objects and libraries.
 # -debug : produce debugging information to debug the libraries.
+# Get gcc version and set GCCVERS* variables
+
+Set_GCCVERS()
+{
+ GCCVERS=`env LANG=C $CC -v 2>&1  | grep "gcc version" | cut -f 3 -d " "`
+ if [ "$GCCVERS" = "" ]; then
+  GCCVERS_MAJOR=0
+  GCCVERS_MINOR=0
+  GCCVERS_UPDATE=0
+ else
+  GCCVERS_MAJOR=`echo $GCCVERS | cut -f 1 -d "."`
+  GCCVERS_MINOR=`echo $GCCVERS | cut -f 2 -d "."`
+  GCCVERS_UPDATE=`echo $GCCVERS | cut -f 3 -d "."`
+ fi
+}
+
 
 if [ "${MW_MACHINETYPE}" = "" ]; then
    echo "Please set the \$MW_MACHINETYPE environment variable"
@@ -86,6 +102,21 @@ done
 echo "=== `date`"
 echo "=== Install the MegaWave2 kernel ==="
 
+
+CC=cc; Set_GCCVERS
+#echo "GCCVERS major=$GCCVERS_MAJOR minor=$GCCVERS_MINOR update=$GCCVERS_UPDATE"
+# Shortcoming to fix bug number 84115 in gcc-4.1 (Ubuntu).
+# See in the future if gcc 4.2 does not need this workaround.
+if [ $GCCVERS_MAJOR -eq 4 ]; then
+ if [ $GCCVERS_MINOR -ge 1 ]; then
+  if [ $debug -eq 1 ]; then
+   echo "=== Warning : with gcc ${GCCVERS_MAJOR}.${GCCVERS_MINOR} libraries cannot be compiled with debug option !" 2>&1
+  fi
+  libopt="$libopt -nofstackprotector"
+  echo "=== Warning : with gcc ${GCCVERS_MAJOR}.${GCCVERS_MINOR}, I set flag -fno-stack-protector !" 2>&1
+ fi
+fi
+
 cd $CWD/Wdevice
 ./Install $libopt
 if [ $? -ne 0 ]; then
@@ -101,8 +132,19 @@ fi
 cd  $CWD/mwp
 ./Install $mwpopt
 if [ $? -ne 0 ]; then
-  echo "=== Error in mwp Install ! Abort kernel Install. ===" 2>&1
-  exit 1
+  echo "=== Error in mwp Install ! Second chance with mwplight... ===" 2>&1
+  mwpok=0
+else
+  mwpok=1
+fi
+cd  $CWD/mwplight
+./Install $mwpopt
+if [ $? -ne 0 ]; then
+  if [ $mwpok -eq 0 ]; then
+   echo "=== Error in mwplight Install ! No preprocessor available : abort kernel Install. ===" 2>&1
+   exit 1
+  fi
+  echo "=== Error in mwplight Install ! You will have to use traditional mwp only ===" 2>&1
 fi
 
 cd $CWD/shell
diff --git a/kernel/shell/mwcmwcheck b/kernel/shell/mwcmwcheck
--- a/kernel/shell/mwcmwcheck
+++ b/kernel/shell/mwcmwcheck
@@ -2,8 +2,8 @@
 #--------------------------- Shell MegaWave Macro ----------------------------#
 _sccsid="%Z%MegaWave2 %R%, %M% %I%, %G%";
 _Prog="mwcmwcheck"
-_Vers="1.0";
-_Date="2001";
+_Vers="1.2";
+_Date="2001-2006";
 _Func="Check the MegaWave2 compiler";
 _Auth="Jacques Froment";
 _Usage=""
@@ -17,6 +17,17 @@ _Usage=""
 #       94235 Cachan cedex, France. Email: megawave@cmla.ens-cachan.fr 
 #-----------------------------------------------------------------------------
 
+# Error code returned :
+# 0 : MegaWave2 compiler successively checked for all given modules and
+#     using both the 'traditional' preprocessor and the 'light' one.
+# 1 : None modules could be checked.
+# 2 : The compilation using the 'traditional' preprocessor failed for
+#     at least one module, and so one using the 'light' one.
+# 3 : The compilation using the 'traditional' preprocessor failed for
+#     at least one module, but all computations worked for the 'light' one.
+# 4 : The compilation using the 'light' preprocessor failed for
+#     at least one module, but all worked for the 'traditional' one.
+
 # Check input
 if [ $# -ne 0 ]; then
    . .mw2_help_lg_com
@@ -27,6 +38,10 @@ fi
 # that is that does not depend to another module.
 
 modlist="ccopy"
+
+# Check result with mwp ('traditional' preprocessor) and mwplight (the 'light' one)
+mwp=1
+mwplight=1
 
 oneok=0
 for mod in $modlist
@@ -39,14 +54,25 @@ do
   if [ ! -w $loc ]; then
    echo "Warning: compiler cannot be checked on module \"$mod\" ! (no write permission on \"$loc\")"  1>&2
   else
-   (cd $loc; cmw2 -N $mod >> /dev/null 2>> /dev/null;)
+   (cd $loc; cmw2 -N -traditional $mod >> /dev/null 2>> /dev/null;)
    if [ $? -ne 0 ]; then
-    echo "Module \"$mod\" cannot be compiled !" 1>&2
+    mwp=0
+    echo "Module \"$mod\" cannot be compiled using the 'traditional' preprocessor !" 1>&2
     echo "Following the corresponding output. Please send these lines when reporting bugs:" 1>&2
     echo "--------------------------------------------------------------------------------" 1>&2 
-    (cd $loc; cmw2 -N $mod)
+    (cd $loc; cmw2 -N -traditional $mod)
     echo "--------------------------------------------------------------------------------" 1>&2 
-    exit 1
+   else
+    oneok=1
+   fi
+   (cd $loc; cmw2 -N -light $mod >> /dev/null 2>> /dev/null;)
+   if [ $? -ne 0 ]; then
+    mwplight=0
+    echo "Module \"$mod\" cannot be compiled using the 'light' preprocessor !" 1>&2
+    echo "Following the corresponding output. Please send these lines when reporting bugs:" 1>&2
+    echo "--------------------------------------------------------------------------------" 1>&2 
+    (cd $loc; cmw2 -N -light $mod)
+    echo "--------------------------------------------------------------------------------" 1>&2 
    else
     oneok=1
    fi
@@ -55,8 +81,20 @@ do
 done
 
 if [ $oneok -eq 0 ]; then
- echo "Error: zero module compiled !"  1>&2
+ echo "Error: zero module successfully compiled !"  1>&2
  exit 1
+fi
+
+if [ $mwp -eq 0 ] && [ $mwplight -eq 0 ]; then
+ exit 2
+fi
+
+if [ $mwp -eq 0 ]; then
+ exit 3
+fi
+
+if [ $mwplight -eq 0 ]; then
+ exit 4
 fi
 
 exit 0
diff --git a/kernel/shell/mwinstall b/kernel/shell/mwinstall
--- a/kernel/shell/mwinstall
+++ b/kernel/shell/mwinstall
@@ -3,10 +3,10 @@
 _sccsid="%Z%MegaWave %R%, %M% %I%, %G%";
 _Func="Install a new MegaWave2 full version (adm only)";
 _Prog="`basename $0`"
-_Vers="1.23"
-_Date="1999-2003"
+_Vers="1.27"
+_Date="1999-2006"
 _Auth="Jacques Froment";
-_Usage="[-static] [-public || -public=private] [-clear] [-debug] [-level l] mw2distribution"
+_Usage="[-static] [-public || -public=private] [-clear] [-debug] [-level l] [-traditional] mw2distribution"
 #-----------------------------------------------------------------------------
 # This file is part of the MegaWave2 kernel.
 # MegaWave2 is a "soft-publication" for the scientific community. It has
@@ -29,6 +29,8 @@ _Usage="[-static] [-public || -public=private] [-clear] [-debug] [-level l] mw2d
 #          option may be required to perform the action you expect.
 # -debug : Produce debugging information (default : optimize the code).
 # -level l : Install levels greater or equal than l only.
+# -traditional : Compile modules using the 'traditional' preprocessor mwp (by default, 
+#          it uses the new 'light' preprocessor if possible).
 #-----------------------------------------------------------------------------
 
 ChooseTMP()
@@ -125,6 +127,7 @@ kernelopt=""
 ChooseTMP
 cmw2trace=${TMP}/cmw2_all$$.trace
 cmw2opt="-2p -dep -force -v $cmw2trace"
+preferredmwp="mwplight"
 
 setenvopt="-privateonly"
 l=1
@@ -163,6 +166,11 @@ do
 	  "-level") l=$2
 		    shift; shift
 		    ;;
+
+	  "-traditional") preferredmwp="mwp"
+		    shift
+		    ;;
+
 	  
            -*)      . .mw2_help_lg_com
                 ;;
@@ -363,14 +371,31 @@ if [ $l -le $level ]; then
  Echo "***** Level $level : Compile the modules *****"
  Echo "*****************************************"
 
-# Check if cmw2 works well. If not, output error message from cmw2
+# Check if cmw2 works well and using which preprocessor. If not, output error message from cmw2
 # so the user can guess what is happening.
  
  mwcmwcheck
- if [ $? -ne 0 ]; then
+ res=$?
+ if [ $res -eq 1 ] ||  [ $res -eq 2 ]; then
    Echo "***** Modules cannot be compiled ! It means something went wrong during the kernel installation stage..." 
    Abort
  fi
+ if [ $res -eq 3 ]; then
+  if [ "$preferredmwp" != "mwplight" ]; then
+   Echo "***** Modules cannot be compiled using the 'traditional' preprocessor ! Switching to the 'light' one..." 
+   preferredmwp="mwplight"
+  fi
+ fi
+ if [ $res -eq 4 ]; then
+  if [ "$preferredmwp" != "mwp" ]; then
+   Echo "***** Modules cannot be compiled using the 'light' preprocessor ! Switching to the 'traditional' one..." 
+   preferredmwp="mwp"
+  fi
+ fi 
+ if [ "$preferredmwp" = "mwp" ]; then
+  cmw2opt="${cmw2opt} -traditional"
+ fi
+
 
 # Now, compile all modules.
 
@@ -605,7 +630,7 @@ Echo " "
 trap "Echo '***** Checking of modules aborted'; exit 1" 2 3
 chk=`mwwhere -bin Checkmodules`
 if [ "$chk" != "" ]; then
-  Answer "***** Do you want to check the module library" "N"
+  Answer "***** Do you want to check the module library" "Y"
   if [ "$ans" = "Y" ]; then
     MW_CHECK_HIDDEN=1
     export MW_CHECK_HIDDEN
